FROM python:3.12.8
#run docker container of python 3.12.8

#tell it to install pandas for csv/parquet files
#also psycopg2 pyarrow and fastparquet for conversion from pq to csv
RUN pip install pandas sqlalchemy psycopg2 pyarrow fastparquet
#install wget for download
RUN apt-get install wget

#what directory to start in
WORKDIR /app
#copy file from host machine int to docker
COPY ingest_zones.py ingest_zones.py
COPY ingest_green.py ingest_green.py

#run in python and run ingestion scripts for green taxi data as well as zone data
#this prepares the databases
ENTRYPOINT [ "python", "ingest_green.py", "ingest_zones.py" ]